
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("b102f26f-3ab1-4ba4-b2f8-bfa03447e47b")>
#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class flguEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new flguEntities object using the connection string found in the 'flguEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=flguEntities", "flguEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new flguEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "flguEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new flguEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "flguEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property barangays() As ObjectSet(Of barangay)
        Get
            If (_barangays Is Nothing) Then
                _barangays = MyBase.CreateObjectSet(Of barangay)("barangays")
            End If
            Return _barangays
        End Get
    End Property

    Private _barangays As ObjectSet(Of barangay)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property cities() As ObjectSet(Of city)
        Get
            If (_cities Is Nothing) Then
                _cities = MyBase.CreateObjectSet(Of city)("cities")
            End If
            Return _cities
        End Get
    End Property

    Private _cities As ObjectSet(Of city)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property diseases() As ObjectSet(Of disease)
        Get
            If (_diseases Is Nothing) Then
                _diseases = MyBase.CreateObjectSet(Of disease)("diseases")
            End If
            Return _diseases
        End Get
    End Property

    Private _diseases As ObjectSet(Of disease)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property logs() As ObjectSet(Of log)
        Get
            If (_logs Is Nothing) Then
                _logs = MyBase.CreateObjectSet(Of log)("logs")
            End If
            Return _logs
        End Get
    End Property

    Private _logs As ObjectSet(Of log)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property puroks() As ObjectSet(Of purok)
        Get
            If (_puroks Is Nothing) Then
                _puroks = MyBase.CreateObjectSet(Of purok)("puroks")
            End If
            Return _puroks
        End Get
    End Property

    Private _puroks As ObjectSet(Of purok)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property socialstatus() As ObjectSet(Of socialstatu)
        Get
            If (_socialstatus Is Nothing) Then
                _socialstatus = MyBase.CreateObjectSet(Of socialstatu)("socialstatus")
            End If
            Return _socialstatus
        End Get
    End Property

    Private _socialstatus As ObjectSet(Of socialstatu)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property households() As ObjectSet(Of household)
        Get
            If (_households Is Nothing) Then
                _households = MyBase.CreateObjectSet(Of household)("households")
            End If
            Return _households
        End Get
    End Property

    Private _households As ObjectSet(Of household)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property citizens() As ObjectSet(Of citizen)
        Get
            If (_citizens Is Nothing) Then
                _citizens = MyBase.CreateObjectSet(Of citizen)("citizens")
            End If
            Return _citizens
        End Get
    End Property

    Private _citizens As ObjectSet(Of citizen)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property accounts() As ObjectSet(Of account)
        Get
            If (_accounts Is Nothing) Then
                _accounts = MyBase.CreateObjectSet(Of account)("accounts")
            End If
            Return _accounts
        End Get
    End Property

    Private _accounts As ObjectSet(Of account)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property occupations() As ObjectSet(Of occupation)
        Get
            If (_occupations Is Nothing) Then
                _occupations = MyBase.CreateObjectSet(Of occupation)("occupations")
            End If
            Return _occupations
        End Get
    End Property

    Private _occupations As ObjectSet(Of occupation)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property citizencategories() As ObjectSet(Of citizencategory)
        Get
            If (_citizencategories Is Nothing) Then
                _citizencategories = MyBase.CreateObjectSet(Of citizencategory)("citizencategories")
            End If
            Return _citizencategories
        End Get
    End Property

    Private _citizencategories As ObjectSet(Of citizencategory)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the barangays EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTobarangays(ByVal barangay As barangay)
        MyBase.AddObject("barangays", barangay)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the cities EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTocities(ByVal city As city)
        MyBase.AddObject("cities", city)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the diseases EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTodiseases(ByVal disease As disease)
        MyBase.AddObject("diseases", disease)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the logs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTologs(ByVal log As log)
        MyBase.AddObject("logs", log)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the puroks EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTopuroks(ByVal purok As purok)
        MyBase.AddObject("puroks", purok)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the socialstatus EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTosocialstatus(ByVal socialstatu As socialstatu)
        MyBase.AddObject("socialstatus", socialstatu)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the households EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTohouseholds(ByVal household As household)
        MyBase.AddObject("households", household)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the citizens EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTocitizens(ByVal citizen As citizen)
        MyBase.AddObject("citizens", citizen)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the accounts EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToaccounts(ByVal account As account)
        MyBase.AddObject("accounts", account)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the occupations EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTooccupations(ByVal occupation As occupation)
        MyBase.AddObject("occupations", occupation)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the citizencategories EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTocitizencategories(ByVal citizencategory As citizencategory)
        MyBase.AddObject("citizencategories", citizencategory)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="flguModel", Name:="account")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class account
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new account object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="fname">Initial value of the fname property.</param>
    ''' <param name="lname">Initial value of the lname property.</param>
    ''' <param name="mname">Initial value of the mname property.</param>
    ''' <param name="username">Initial value of the username property.</param>
    ''' <param name="password">Initial value of the password property.</param>
    ''' <param name="level">Initial value of the level property.</param>
    ''' <param name="create">Initial value of the create property.</param>
    ''' <param name="edit">Initial value of the edit property.</param>
    ''' <param name="delete">Initial value of the delete property.</param>
    ''' <param name="export">Initial value of the export property.</param>
    ''' <param name="import">Initial value of the import property.</param>
    ''' <param name="remove">Initial value of the remove property.</param>
    Public Shared Function Createaccount(id As Global.System.Int32, fname As Global.System.String, lname As Global.System.String, mname As Global.System.String, username As Global.System.String, password As Global.System.String, level As Global.System.Int32, create As Global.System.Boolean, edit As Global.System.Boolean, delete As Global.System.Boolean, export As Global.System.Boolean, import As Global.System.Boolean, remove As Global.System.Boolean) As account
        Dim account as account = New account
        account.id = id
        account.fname = fname
        account.lname = lname
        account.mname = mname
        account.username = username
        account.password = password
        account.level = level
        account.create = create
        account.edit = edit
        account.delete = delete
        account.export = export
        account.import = import
        account.remove = remove
        Return account
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property fname() As Global.System.String
        Get
            Return _fname
        End Get
        Set
            OnfnameChanging(value)
            ReportPropertyChanging("fname")
            _fname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("fname")
            OnfnameChanged()
        End Set
    End Property

    Private _fname As Global.System.String
    Private Partial Sub OnfnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property lname() As Global.System.String
        Get
            Return _lname
        End Get
        Set
            OnlnameChanging(value)
            ReportPropertyChanging("lname")
            _lname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("lname")
            OnlnameChanged()
        End Set
    End Property

    Private _lname As Global.System.String
    Private Partial Sub OnlnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnlnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property mname() As Global.System.String
        Get
            Return _mname
        End Get
        Set
            OnmnameChanging(value)
            ReportPropertyChanging("mname")
            _mname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("mname")
            OnmnameChanged()
        End Set
    End Property

    Private _mname As Global.System.String
    Private Partial Sub OnmnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnmnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property username() As Global.System.String
        Get
            Return _username
        End Get
        Set
            OnusernameChanging(value)
            ReportPropertyChanging("username")
            _username = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("username")
            OnusernameChanged()
        End Set
    End Property

    Private _username As Global.System.String
    Private Partial Sub OnusernameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnusernameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property password() As Global.System.String
        Get
            Return _password
        End Get
        Set
            OnpasswordChanging(value)
            ReportPropertyChanging("password")
            _password = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("password")
            OnpasswordChanged()
        End Set
    End Property

    Private _password As Global.System.String
    Private Partial Sub OnpasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnpasswordChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property level() As Global.System.Int32
        Get
            Return _level
        End Get
        Set
            OnlevelChanging(value)
            ReportPropertyChanging("level")
            _level = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("level")
            OnlevelChanged()
        End Set
    End Property

    Private _level As Global.System.Int32
    Private Partial Sub OnlevelChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnlevelChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property create() As Global.System.Boolean
        Get
            Return _create
        End Get
        Set
            OncreateChanging(value)
            ReportPropertyChanging("create")
            _create = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create")
            OncreateChanged()
        End Set
    End Property

    Private _create As Global.System.Boolean
    Private Partial Sub OncreateChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OncreateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property edit() As Global.System.Boolean
        Get
            Return _edit
        End Get
        Set
            OneditChanging(value)
            ReportPropertyChanging("edit")
            _edit = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("edit")
            OneditChanged()
        End Set
    End Property

    Private _edit As Global.System.Boolean
    Private Partial Sub OneditChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OneditChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property delete() As Global.System.Boolean
        Get
            Return _delete
        End Get
        Set
            OndeleteChanging(value)
            ReportPropertyChanging("delete")
            _delete = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delete")
            OndeleteChanged()
        End Set
    End Property

    Private _delete As Global.System.Boolean
    Private Partial Sub OndeleteChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OndeleteChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property export() As Global.System.Boolean
        Get
            Return _export
        End Get
        Set
            OnexportChanging(value)
            ReportPropertyChanging("export")
            _export = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("export")
            OnexportChanged()
        End Set
    End Property

    Private _export As Global.System.Boolean
    Private Partial Sub OnexportChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnexportChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property import() As Global.System.Boolean
        Get
            Return _import
        End Get
        Set
            OnimportChanging(value)
            ReportPropertyChanging("import")
            _import = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("import")
            OnimportChanged()
        End Set
    End Property

    Private _import As Global.System.Boolean
    Private Partial Sub OnimportChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnimportChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property remove() As Global.System.Boolean
        Get
            Return _remove
        End Get
        Set
            OnremoveChanging(value)
            ReportPropertyChanging("remove")
            _remove = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("remove")
            OnremoveChanged()
        End Set
    End Property

    Private _remove As Global.System.Boolean
    Private Partial Sub OnremoveChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnremoveChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="flguModel", Name:="barangay")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class barangay
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new barangay object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="name">Initial value of the name property.</param>
    ''' <param name="datecreated">Initial value of the datecreated property.</param>
    ''' <param name="cityid">Initial value of the cityid property.</param>
    ''' <param name="remove">Initial value of the remove property.</param>
    Public Shared Function Createbarangay(id As Global.System.Int32, name As Global.System.String, datecreated As Global.System.DateTime, cityid As Global.System.Int32, remove As Global.System.Boolean) As barangay
        Dim barangay as barangay = New barangay
        barangay.id = id
        barangay.name = name
        barangay.datecreated = datecreated
        barangay.cityid = cityid
        barangay.remove = remove
        Return barangay
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property datecreated() As Global.System.DateTime
        Get
            Return _datecreated
        End Get
        Set
            OndatecreatedChanging(value)
            ReportPropertyChanging("datecreated")
            _datecreated = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("datecreated")
            OndatecreatedChanged()
        End Set
    End Property

    Private _datecreated As Global.System.DateTime
    Private Partial Sub OndatecreatedChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OndatecreatedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property cityid() As Global.System.Int32
        Get
            Return _cityid
        End Get
        Set
            OncityidChanging(value)
            ReportPropertyChanging("cityid")
            _cityid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("cityid")
            OncityidChanged()
        End Set
    End Property

    Private _cityid As Global.System.Int32
    Private Partial Sub OncityidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OncityidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property remove() As Global.System.Boolean
        Get
            Return _remove
        End Get
        Set
            OnremoveChanging(value)
            ReportPropertyChanging("remove")
            _remove = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("remove")
            OnremoveChanged()
        End Set
    End Property

    Private _remove As Global.System.Boolean
    Private Partial Sub OnremoveChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnremoveChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="flguModel", Name:="citizen")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class citizen
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new citizen object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="hid">Initial value of the hid property.</param>
    ''' <param name="fname">Initial value of the fname property.</param>
    ''' <param name="lname">Initial value of the lname property.</param>
    ''' <param name="mname">Initial value of the mname property.</param>
    ''' <param name="birthdate">Initial value of the birthdate property.</param>
    ''' <param name="contactnum">Initial value of the contactnum property.</param>
    ''' <param name="tin">Initial value of the tin property.</param>
    ''' <param name="philhealth">Initial value of the philhealth property.</param>
    ''' <param name="philhealthtype">Initial value of the philhealthtype property.</param>
    ''' <param name="philhealthexp">Initial value of the philhealthexp property.</param>
    ''' <param name="income">Initial value of the income property.</param>
    ''' <param name="bloodtypeid">Initial value of the bloodtypeid property.</param>
    ''' <param name="occupation">Initial value of the occupation property.</param>
    ''' <param name="osyisy">Initial value of the osyisy property.</param>
    ''' <param name="pwe">Initial value of the pwe property.</param>
    ''' <param name="diseased">Initial value of the diseased property.</param>
    ''' <param name="gender">Initial value of the Gender property.</param>
    ''' <param name="category">Initial value of the category property.</param>
    ''' <param name="datecreated">Initial value of the datecreated property.</param>
    ''' <param name="remove">Initial value of the remove property.</param>
    Public Shared Function Createcitizen(id As Global.System.Int32, hid As Global.System.Int32, fname As Global.System.String, lname As Global.System.String, mname As Global.System.String, birthdate As Global.System.DateTime, contactnum As Global.System.String, tin As Global.System.String, philhealth As Global.System.String, philhealthtype As Global.System.Int32, philhealthexp As Global.System.DateTime, income As Global.System.String, bloodtypeid As Global.System.String, occupation As Global.System.Int32, osyisy As Global.System.String, pwe As Global.System.String, diseased As Global.System.Int32, gender As Global.System.String, category As Global.System.Int32, datecreated As Global.System.DateTime, remove As Global.System.Boolean) As citizen
        Dim citizen as citizen = New citizen
        citizen.id = id
        citizen.hid = hid
        citizen.fname = fname
        citizen.lname = lname
        citizen.mname = mname
        citizen.birthdate = birthdate
        citizen.contactnum = contactnum
        citizen.tin = tin
        citizen.philhealth = philhealth
        citizen.philhealthtype = philhealthtype
        citizen.philhealthexp = philhealthexp
        citizen.income = income
        citizen.bloodtypeid = bloodtypeid
        citizen.occupation = occupation
        citizen.osyisy = osyisy
        citizen.pwe = pwe
        citizen.diseased = diseased
        citizen.Gender = gender
        citizen.category = category
        citizen.datecreated = datecreated
        citizen.remove = remove
        Return citizen
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property hid() As Global.System.Int32
        Get
            Return _hid
        End Get
        Set
            OnhidChanging(value)
            ReportPropertyChanging("hid")
            _hid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("hid")
            OnhidChanged()
        End Set
    End Property

    Private _hid As Global.System.Int32
    Private Partial Sub OnhidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnhidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property fname() As Global.System.String
        Get
            Return _fname
        End Get
        Set
            OnfnameChanging(value)
            ReportPropertyChanging("fname")
            _fname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("fname")
            OnfnameChanged()
        End Set
    End Property

    Private _fname As Global.System.String
    Private Partial Sub OnfnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property lname() As Global.System.String
        Get
            Return _lname
        End Get
        Set
            OnlnameChanging(value)
            ReportPropertyChanging("lname")
            _lname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("lname")
            OnlnameChanged()
        End Set
    End Property

    Private _lname As Global.System.String
    Private Partial Sub OnlnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnlnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property mname() As Global.System.String
        Get
            Return _mname
        End Get
        Set
            OnmnameChanging(value)
            ReportPropertyChanging("mname")
            _mname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("mname")
            OnmnameChanged()
        End Set
    End Property

    Private _mname As Global.System.String
    Private Partial Sub OnmnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnmnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property birthdate() As Global.System.DateTime
        Get
            Return _birthdate
        End Get
        Set
            OnbirthdateChanging(value)
            ReportPropertyChanging("birthdate")
            _birthdate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("birthdate")
            OnbirthdateChanged()
        End Set
    End Property

    Private _birthdate As Global.System.DateTime
    Private Partial Sub OnbirthdateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnbirthdateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property contactnum() As Global.System.String
        Get
            Return _contactnum
        End Get
        Set
            OncontactnumChanging(value)
            ReportPropertyChanging("contactnum")
            _contactnum = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("contactnum")
            OncontactnumChanged()
        End Set
    End Property

    Private _contactnum As Global.System.String
    Private Partial Sub OncontactnumChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncontactnumChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property tin() As Global.System.String
        Get
            Return _tin
        End Get
        Set
            OntinChanging(value)
            ReportPropertyChanging("tin")
            _tin = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("tin")
            OntinChanged()
        End Set
    End Property

    Private _tin As Global.System.String
    Private Partial Sub OntinChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OntinChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property philhealth() As Global.System.String
        Get
            Return _philhealth
        End Get
        Set
            OnphilhealthChanging(value)
            ReportPropertyChanging("philhealth")
            _philhealth = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("philhealth")
            OnphilhealthChanged()
        End Set
    End Property

    Private _philhealth As Global.System.String
    Private Partial Sub OnphilhealthChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnphilhealthChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property philhealthtype() As Global.System.Int32
        Get
            Return _philhealthtype
        End Get
        Set
            OnphilhealthtypeChanging(value)
            ReportPropertyChanging("philhealthtype")
            _philhealthtype = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("philhealthtype")
            OnphilhealthtypeChanged()
        End Set
    End Property

    Private _philhealthtype As Global.System.Int32
    Private Partial Sub OnphilhealthtypeChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnphilhealthtypeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property philhealthexp() As Global.System.DateTime
        Get
            Return _philhealthexp
        End Get
        Set
            OnphilhealthexpChanging(value)
            ReportPropertyChanging("philhealthexp")
            _philhealthexp = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("philhealthexp")
            OnphilhealthexpChanged()
        End Set
    End Property

    Private _philhealthexp As Global.System.DateTime
    Private Partial Sub OnphilhealthexpChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnphilhealthexpChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property income() As Global.System.String
        Get
            Return _income
        End Get
        Set
            OnincomeChanging(value)
            ReportPropertyChanging("income")
            _income = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("income")
            OnincomeChanged()
        End Set
    End Property

    Private _income As Global.System.String
    Private Partial Sub OnincomeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnincomeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property bloodtypeid() As Global.System.String
        Get
            Return _bloodtypeid
        End Get
        Set
            OnbloodtypeidChanging(value)
            ReportPropertyChanging("bloodtypeid")
            _bloodtypeid = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("bloodtypeid")
            OnbloodtypeidChanged()
        End Set
    End Property

    Private _bloodtypeid As Global.System.String
    Private Partial Sub OnbloodtypeidChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnbloodtypeidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property occupation() As Global.System.Int32
        Get
            Return _occupation
        End Get
        Set
            OnoccupationChanging(value)
            ReportPropertyChanging("occupation")
            _occupation = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("occupation")
            OnoccupationChanged()
        End Set
    End Property

    Private _occupation As Global.System.Int32
    Private Partial Sub OnoccupationChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnoccupationChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property osyisy() As Global.System.String
        Get
            Return _osyisy
        End Get
        Set
            OnosyisyChanging(value)
            ReportPropertyChanging("osyisy")
            _osyisy = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("osyisy")
            OnosyisyChanged()
        End Set
    End Property

    Private _osyisy As Global.System.String
    Private Partial Sub OnosyisyChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnosyisyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property pwe() As Global.System.String
        Get
            Return _pwe
        End Get
        Set
            OnpweChanging(value)
            ReportPropertyChanging("pwe")
            _pwe = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("pwe")
            OnpweChanged()
        End Set
    End Property

    Private _pwe As Global.System.String
    Private Partial Sub OnpweChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnpweChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property diseased() As Global.System.Int32
        Get
            Return _diseased
        End Get
        Set
            OndiseasedChanging(value)
            ReportPropertyChanging("diseased")
            _diseased = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("diseased")
            OndiseasedChanged()
        End Set
    End Property

    Private _diseased As Global.System.Int32
    Private Partial Sub OndiseasedChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OndiseasedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Gender() As Global.System.String
        Get
            Return _Gender
        End Get
        Set
            OnGenderChanging(value)
            ReportPropertyChanging("Gender")
            _Gender = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Gender")
            OnGenderChanged()
        End Set
    End Property

    Private _Gender As Global.System.String
    Private Partial Sub OnGenderChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnGenderChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property category() As Global.System.Int32
        Get
            Return _category
        End Get
        Set
            OncategoryChanging(value)
            ReportPropertyChanging("category")
            _category = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("category")
            OncategoryChanged()
        End Set
    End Property

    Private _category As Global.System.Int32
    Private Partial Sub OncategoryChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OncategoryChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property datecreated() As Global.System.DateTime
        Get
            Return _datecreated
        End Get
        Set
            OndatecreatedChanging(value)
            ReportPropertyChanging("datecreated")
            _datecreated = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("datecreated")
            OndatecreatedChanged()
        End Set
    End Property

    Private _datecreated As Global.System.DateTime
    Private Partial Sub OndatecreatedChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OndatecreatedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property remove() As Global.System.Boolean
        Get
            Return _remove
        End Get
        Set
            OnremoveChanging(value)
            ReportPropertyChanging("remove")
            _remove = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("remove")
            OnremoveChanged()
        End Set
    End Property

    Private _remove As Global.System.Boolean
    Private Partial Sub OnremoveChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnremoveChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="flguModel", Name:="citizencategory")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class citizencategory
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new citizencategory object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="name">Initial value of the name property.</param>
    ''' <param name="creation">Initial value of the creation property.</param>
    ''' <param name="remove">Initial value of the remove property.</param>
    Public Shared Function Createcitizencategory(id As Global.System.Int32, name As Global.System.String, creation As Global.System.DateTime, remove As Global.System.Boolean) As citizencategory
        Dim citizencategory as citizencategory = New citizencategory
        citizencategory.id = id
        citizencategory.name = name
        citizencategory.creation = creation
        citizencategory.remove = remove
        Return citizencategory
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property creation() As Global.System.DateTime
        Get
            Return _creation
        End Get
        Set
            OncreationChanging(value)
            ReportPropertyChanging("creation")
            _creation = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("creation")
            OncreationChanged()
        End Set
    End Property

    Private _creation As Global.System.DateTime
    Private Partial Sub OncreationChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OncreationChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property remove() As Global.System.Boolean
        Get
            Return _remove
        End Get
        Set
            OnremoveChanging(value)
            ReportPropertyChanging("remove")
            _remove = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("remove")
            OnremoveChanged()
        End Set
    End Property

    Private _remove As Global.System.Boolean
    Private Partial Sub OnremoveChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnremoveChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="flguModel", Name:="city")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class city
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new city object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="name">Initial value of the name property.</param>
    ''' <param name="datecreated">Initial value of the datecreated property.</param>
    ''' <param name="remove">Initial value of the remove property.</param>
    Public Shared Function Createcity(id As Global.System.Int32, name As Global.System.String, datecreated As Global.System.DateTime, remove As Global.System.Boolean) As city
        Dim city as city = New city
        city.id = id
        city.name = name
        city.datecreated = datecreated
        city.remove = remove
        Return city
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property datecreated() As Global.System.DateTime
        Get
            Return _datecreated
        End Get
        Set
            OndatecreatedChanging(value)
            ReportPropertyChanging("datecreated")
            _datecreated = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("datecreated")
            OndatecreatedChanged()
        End Set
    End Property

    Private _datecreated As Global.System.DateTime
    Private Partial Sub OndatecreatedChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OndatecreatedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property remove() As Global.System.Boolean
        Get
            Return _remove
        End Get
        Set
            OnremoveChanging(value)
            ReportPropertyChanging("remove")
            _remove = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("remove")
            OnremoveChanged()
        End Set
    End Property

    Private _remove As Global.System.Boolean
    Private Partial Sub OnremoveChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnremoveChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="flguModel", Name:="disease")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class disease
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new disease object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="name">Initial value of the name property.</param>
    ''' <param name="datecreated">Initial value of the datecreated property.</param>
    ''' <param name="remove">Initial value of the remove property.</param>
    Public Shared Function Createdisease(id As Global.System.Int32, name As Global.System.String, datecreated As Global.System.DateTime, remove As Global.System.Boolean) As disease
        Dim disease as disease = New disease
        disease.id = id
        disease.name = name
        disease.datecreated = datecreated
        disease.remove = remove
        Return disease
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property datecreated() As Global.System.DateTime
        Get
            Return _datecreated
        End Get
        Set
            OndatecreatedChanging(value)
            ReportPropertyChanging("datecreated")
            _datecreated = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("datecreated")
            OndatecreatedChanged()
        End Set
    End Property

    Private _datecreated As Global.System.DateTime
    Private Partial Sub OndatecreatedChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OndatecreatedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property remove() As Global.System.Boolean
        Get
            Return _remove
        End Get
        Set
            OnremoveChanging(value)
            ReportPropertyChanging("remove")
            _remove = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("remove")
            OnremoveChanged()
        End Set
    End Property

    Private _remove As Global.System.Boolean
    Private Partial Sub OnremoveChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnremoveChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="flguModel", Name:="household")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class household
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new household object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="hnumber">Initial value of the hnumber property.</param>
    ''' <param name="famid">Initial value of the famid property.</param>
    ''' <param name="socialCommunity">Initial value of the SocialCommunity property.</param>
    ''' <param name="familyname">Initial value of the familyname property.</param>
    ''' <param name="datecreated">Initial value of the datecreated property.</param>
    ''' <param name="purokid">Initial value of the purokid property.</param>
    ''' <param name="cityid">Initial value of the cityid property.</param>
    ''' <param name="barangayid">Initial value of the barangayid property.</param>
    ''' <param name="categoryid">Initial value of the categoryid property.</param>
    ''' <param name="remove">Initial value of the remove property.</param>
    Public Shared Function Createhousehold(id As Global.System.Int32, hnumber As Global.System.Int32, famid As Global.System.Int32, socialCommunity As Global.System.Int32, familyname As Global.System.String, datecreated As Global.System.DateTime, purokid As Global.System.Int32, cityid As Global.System.Int32, barangayid As Global.System.Int32, categoryid As Global.System.Int32, remove As Global.System.Boolean) As household
        Dim household as household = New household
        household.id = id
        household.hnumber = hnumber
        household.famid = famid
        household.SocialCommunity = socialCommunity
        household.familyname = familyname
        household.datecreated = datecreated
        household.purokid = purokid
        household.cityid = cityid
        household.barangayid = barangayid
        household.categoryid = categoryid
        household.remove = remove
        Return household
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property hnumber() As Global.System.Int32
        Get
            Return _hnumber
        End Get
        Set
            OnhnumberChanging(value)
            ReportPropertyChanging("hnumber")
            _hnumber = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("hnumber")
            OnhnumberChanged()
        End Set
    End Property

    Private _hnumber As Global.System.Int32
    Private Partial Sub OnhnumberChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnhnumberChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property famid() As Global.System.Int32
        Get
            Return _famid
        End Get
        Set
            OnfamidChanging(value)
            ReportPropertyChanging("famid")
            _famid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("famid")
            OnfamidChanged()
        End Set
    End Property

    Private _famid As Global.System.Int32
    Private Partial Sub OnfamidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnfamidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SocialCommunity() As Global.System.Int32
        Get
            Return _SocialCommunity
        End Get
        Set
            OnSocialCommunityChanging(value)
            ReportPropertyChanging("SocialCommunity")
            _SocialCommunity = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SocialCommunity")
            OnSocialCommunityChanged()
        End Set
    End Property

    Private _SocialCommunity As Global.System.Int32
    Private Partial Sub OnSocialCommunityChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnSocialCommunityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property familyname() As Global.System.String
        Get
            Return _familyname
        End Get
        Set
            OnfamilynameChanging(value)
            ReportPropertyChanging("familyname")
            _familyname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("familyname")
            OnfamilynameChanged()
        End Set
    End Property

    Private _familyname As Global.System.String
    Private Partial Sub OnfamilynameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfamilynameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property datecreated() As Global.System.DateTime
        Get
            Return _datecreated
        End Get
        Set
            OndatecreatedChanging(value)
            ReportPropertyChanging("datecreated")
            _datecreated = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("datecreated")
            OndatecreatedChanged()
        End Set
    End Property

    Private _datecreated As Global.System.DateTime
    Private Partial Sub OndatecreatedChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OndatecreatedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property purokid() As Global.System.Int32
        Get
            Return _purokid
        End Get
        Set
            OnpurokidChanging(value)
            ReportPropertyChanging("purokid")
            _purokid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("purokid")
            OnpurokidChanged()
        End Set
    End Property

    Private _purokid As Global.System.Int32
    Private Partial Sub OnpurokidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnpurokidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property cityid() As Global.System.Int32
        Get
            Return _cityid
        End Get
        Set
            OncityidChanging(value)
            ReportPropertyChanging("cityid")
            _cityid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("cityid")
            OncityidChanged()
        End Set
    End Property

    Private _cityid As Global.System.Int32
    Private Partial Sub OncityidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OncityidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property barangayid() As Global.System.Int32
        Get
            Return _barangayid
        End Get
        Set
            OnbarangayidChanging(value)
            ReportPropertyChanging("barangayid")
            _barangayid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("barangayid")
            OnbarangayidChanged()
        End Set
    End Property

    Private _barangayid As Global.System.Int32
    Private Partial Sub OnbarangayidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnbarangayidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property categoryid() As Global.System.Int32
        Get
            Return _categoryid
        End Get
        Set
            OncategoryidChanging(value)
            ReportPropertyChanging("categoryid")
            _categoryid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("categoryid")
            OncategoryidChanged()
        End Set
    End Property

    Private _categoryid As Global.System.Int32
    Private Partial Sub OncategoryidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OncategoryidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property remove() As Global.System.Boolean
        Get
            Return _remove
        End Get
        Set
            OnremoveChanging(value)
            ReportPropertyChanging("remove")
            _remove = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("remove")
            OnremoveChanged()
        End Set
    End Property

    Private _remove As Global.System.Boolean
    Private Partial Sub OnremoveChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnremoveChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="flguModel", Name:="log")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class log
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new log object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="userid">Initial value of the userid property.</param>
    ''' <param name="action">Initial value of the Action property.</param>
    ''' <param name="tableName">Initial value of the TableName property.</param>
    ''' <param name="recordId">Initial value of the RecordId property.</param>
    ''' <param name="datecreated">Initial value of the datecreated property.</param>
    ''' <param name="remove">Initial value of the remove property.</param>
    Public Shared Function Createlog(id As Global.System.Int32, userid As Global.System.Int32, action As Global.System.String, tableName As Global.System.String, recordId As Global.System.Int32, datecreated As Global.System.DateTime, remove As Global.System.Boolean) As log
        Dim log as log = New log
        log.id = id
        log.userid = userid
        log.Action = action
        log.TableName = tableName
        log.RecordId = recordId
        log.datecreated = datecreated
        log.remove = remove
        Return log
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property userid() As Global.System.Int32
        Get
            Return _userid
        End Get
        Set
            OnuseridChanging(value)
            ReportPropertyChanging("userid")
            _userid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("userid")
            OnuseridChanged()
        End Set
    End Property

    Private _userid As Global.System.Int32
    Private Partial Sub OnuseridChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnuseridChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Action() As Global.System.String
        Get
            Return _Action
        End Get
        Set
            OnActionChanging(value)
            ReportPropertyChanging("Action")
            _Action = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Action")
            OnActionChanged()
        End Set
    End Property

    Private _Action As Global.System.String
    Private Partial Sub OnActionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnActionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property TableName() As Global.System.String
        Get
            Return _TableName
        End Get
        Set
            OnTableNameChanging(value)
            ReportPropertyChanging("TableName")
            _TableName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("TableName")
            OnTableNameChanged()
        End Set
    End Property

    Private _TableName As Global.System.String
    Private Partial Sub OnTableNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTableNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RecordId() As Global.System.Int32
        Get
            Return _RecordId
        End Get
        Set
            OnRecordIdChanging(value)
            ReportPropertyChanging("RecordId")
            _RecordId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("RecordId")
            OnRecordIdChanged()
        End Set
    End Property

    Private _RecordId As Global.System.Int32
    Private Partial Sub OnRecordIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnRecordIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property datecreated() As Global.System.DateTime
        Get
            Return _datecreated
        End Get
        Set
            OndatecreatedChanging(value)
            ReportPropertyChanging("datecreated")
            _datecreated = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("datecreated")
            OndatecreatedChanged()
        End Set
    End Property

    Private _datecreated As Global.System.DateTime
    Private Partial Sub OndatecreatedChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OndatecreatedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property remove() As Global.System.Boolean
        Get
            Return _remove
        End Get
        Set
            OnremoveChanging(value)
            ReportPropertyChanging("remove")
            _remove = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("remove")
            OnremoveChanged()
        End Set
    End Property

    Private _remove As Global.System.Boolean
    Private Partial Sub OnremoveChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnremoveChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="flguModel", Name:="occupation")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class occupation
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new occupation object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="name">Initial value of the name property.</param>
    ''' <param name="datecreated">Initial value of the datecreated property.</param>
    ''' <param name="remove">Initial value of the remove property.</param>
    Public Shared Function Createoccupation(id As Global.System.Int32, name As Global.System.String, datecreated As Global.System.DateTime, remove As Global.System.Boolean) As occupation
        Dim occupation as occupation = New occupation
        occupation.id = id
        occupation.name = name
        occupation.datecreated = datecreated
        occupation.remove = remove
        Return occupation
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property datecreated() As Global.System.DateTime
        Get
            Return _datecreated
        End Get
        Set
            OndatecreatedChanging(value)
            ReportPropertyChanging("datecreated")
            _datecreated = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("datecreated")
            OndatecreatedChanged()
        End Set
    End Property

    Private _datecreated As Global.System.DateTime
    Private Partial Sub OndatecreatedChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OndatecreatedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property remove() As Global.System.Boolean
        Get
            Return _remove
        End Get
        Set
            OnremoveChanging(value)
            ReportPropertyChanging("remove")
            _remove = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("remove")
            OnremoveChanged()
        End Set
    End Property

    Private _remove As Global.System.Boolean
    Private Partial Sub OnremoveChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnremoveChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="flguModel", Name:="purok")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class purok
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new purok object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="name">Initial value of the name property.</param>
    ''' <param name="datecreated">Initial value of the datecreated property.</param>
    ''' <param name="barangayid">Initial value of the barangayid property.</param>
    ''' <param name="remove">Initial value of the remove property.</param>
    Public Shared Function Createpurok(id As Global.System.Int32, name As Global.System.String, datecreated As Global.System.DateTime, barangayid As Global.System.Int32, remove As Global.System.Boolean) As purok
        Dim purok as purok = New purok
        purok.id = id
        purok.name = name
        purok.datecreated = datecreated
        purok.barangayid = barangayid
        purok.remove = remove
        Return purok
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property datecreated() As Global.System.DateTime
        Get
            Return _datecreated
        End Get
        Set
            OndatecreatedChanging(value)
            ReportPropertyChanging("datecreated")
            _datecreated = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("datecreated")
            OndatecreatedChanged()
        End Set
    End Property

    Private _datecreated As Global.System.DateTime
    Private Partial Sub OndatecreatedChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OndatecreatedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property barangayid() As Global.System.Int32
        Get
            Return _barangayid
        End Get
        Set
            OnbarangayidChanging(value)
            ReportPropertyChanging("barangayid")
            _barangayid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("barangayid")
            OnbarangayidChanged()
        End Set
    End Property

    Private _barangayid As Global.System.Int32
    Private Partial Sub OnbarangayidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnbarangayidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property remove() As Global.System.Boolean
        Get
            Return _remove
        End Get
        Set
            OnremoveChanging(value)
            ReportPropertyChanging("remove")
            _remove = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("remove")
            OnremoveChanged()
        End Set
    End Property

    Private _remove As Global.System.Boolean
    Private Partial Sub OnremoveChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnremoveChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="flguModel", Name:="socialstatu")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class socialstatu
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new socialstatu object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="name">Initial value of the name property.</param>
    ''' <param name="description">Initial value of the description property.</param>
    ''' <param name="remove">Initial value of the remove property.</param>
    Public Shared Function Createsocialstatu(id As Global.System.Int32, name As Global.System.String, description As Global.System.String, remove As Global.System.Boolean) As socialstatu
        Dim socialstatu as socialstatu = New socialstatu
        socialstatu.id = id
        socialstatu.name = name
        socialstatu.description = description
        socialstatu.remove = remove
        Return socialstatu
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property description() As Global.System.String
        Get
            Return _description
        End Get
        Set
            OndescriptionChanging(value)
            ReportPropertyChanging("description")
            _description = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("description")
            OndescriptionChanged()
        End Set
    End Property

    Private _description As Global.System.String
    Private Partial Sub OndescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property remove() As Global.System.Boolean
        Get
            Return _remove
        End Get
        Set
            OnremoveChanging(value)
            ReportPropertyChanging("remove")
            _remove = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("remove")
            OnremoveChanged()
        End Set
    End Property

    Private _remove As Global.System.Boolean
    Private Partial Sub OnremoveChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnremoveChanged()
    End Sub

    #End Region

End Class

#End Region


